# Generated by Django 5.2.8 on 2025-11-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RNGModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("python", "Python"),
                            ("java", "Java"),
                            ("cpp", "C++"),
                            ("javascript", "JavaScript"),
                            ("rust", "Rust"),
                            ("go", "Go"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("linear_congruential", "Linear Congruential"),
                            ("mersenne_twister", "Mersenne Twister"),
                            ("xorshift", "XORShift"),
                            ("pcg", "PCG"),
                            ("builtin", "Built-in"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("code_path", models.CharField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "RNG",
                "verbose_name_plural": "RNGs",
                "db_table": "rngs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TestResultModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("test_name", models.CharField(max_length=100)),
                ("passed", models.BooleanField()),
                ("score", models.FloatField()),
                ("execution_time_ms", models.FloatField()),
                ("samples_count", models.IntegerField()),
                ("statistics", models.JSONField()),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rng",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_results",
                        to="infrastructure.rngmodel",
                    ),
                ),
            ],
            options={
                "verbose_name": "Test Result",
                "verbose_name_plural": "Test Results",
                "db_table": "test_results",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="test_result_created_c066b4_idx"
                    ),
                    models.Index(
                        fields=["rng", "-created_at"],
                        name="test_result_rng_id_29b1fa_idx",
                    ),
                ],
            },
        ),
    ]
