# Generated by Django 5.2.8 on 2025-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="rngmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="testresultmodel",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="testresultmodel",
            name="test_result_created_c066b4_idx",
        ),
        migrations.RemoveField(
            model_name="rngmodel",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="rngmodel",
            name="parameters",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rngmodel",
            name="algorithm",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="rngmodel",
            name="language",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="rngmodel",
            name="name",
            field=models.CharField(max_length=200),
        ),
        migrations.AddIndex(
            model_name="testresultmodel",
            index=models.Index(
                fields=["test_name", "-created_at"],
                name="test_result_test_na_e9b442_idx",
            ),
        ),
    ]
