# Generated by Django 5.2.8 on 2025-12-13 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "infrastructure",
            "0002_alter_rngmodel_options_alter_testresultmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="testresultmodel",
            name="generated_bits",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
