# Generated by Django 5.2.8 on 2026-01-05 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("infrastructure", "0003_testresultmodel_generated_bits"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresultmodel",
            name="generated_bits",
        ),
    ]
