# Generated by Django 5.2.8 on 2026-01-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0004_remove_generated_bits_column'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresultmodel',
            name='test_parameters',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
