# Generated by Django 5.2.8 on 2026-01-16 14:50

from django.db import migrations
import sys


def fix_executable_paths(apps, schema_editor):
    """
    Automatically fix executable paths based on OS.

    Windows: .exe files in bin/ or target/release/
    Linux/macOS: native executables without .exe extension
    """
    RNGModel = apps.get_model("infrastructure", "RNGModel")

    # Detect OS
    is_windows = sys.platform == "win32"

    # Define paths for both OS
    if is_windows:
        paths = {
            23: "algorytmy/chacha20_rng/target/release/chacha20_rng.exe",
            24: "algorytmy/Xorshift256/bin/Xoshiro256.exe",
        }
    else:  # Linux/macOS
        paths = {
            23: "algorytmy/chacha20_rng/target/release/chacha20_rng",
            24: "algorytmy/Xorshift256/bin/Release/net9.0/Xoshiro256",
        }

    # Update paths
    for rng_id, new_path in paths.items():
        try:
            rng = RNGModel.objects.get(id=rng_id)
            rng.code_path = new_path
            rng.save()
            print(f"✓ Updated RNG ID {rng_id} ({rng.name}): {new_path}")
        except RNGModel.DoesNotExist:
            print(f"⚠ RNG ID {rng_id} not found in database (skipping)")


def reverse_fix(apps, schema_editor):
    """Reverse migration - reset to Windows paths"""
    RNGModel = apps.get_model("infrastructure", "RNGModel")

    # Default to Windows paths for reverse
    paths = {
        23: "algorytmy/chacha20_rng/target/release/chacha20_rng.exe",
        24: "algorytmy/Xorshift256/bin/Xoshiro256.exe",
    }

    for rng_id, new_path in paths.items():
        try:
            rng = RNGModel.objects.get(id=rng_id)
            rng.code_path = new_path
            rng.save()
        except RNGModel.DoesNotExist:
            pass


class Migration(migrations.Migration):
    dependencies = [
        ("infrastructure", "0005_testresultmodel_test_parameters"),
    ]

    operations = [
        migrations.RunPython(fix_executable_paths, reverse_fix),
    ]
