import React from "react";
import { Document, Page, Text, View, Image, pdf } from "@react-pdf/renderer";
import { styles } from "./ReportStyles";
import type { ReportData } from "@/components/Dashboard/reports/types";

interface PDFReportProps {
  data: ReportData;
}

export const PDFReport: React.FC<PDFReportProps> = ({ data }) => {
  const formatDate = (date: Date) => {
    return new Intl.DateTimeFormat("pl-PL", {
      year: "numeric",
      month: "long",
      day: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    }).format(date);
  };

  const formatNumber = (num: number, decimals: number = 2) => {
    return num.toFixed(decimals);
  };

  return (
    <Document>
      {/* Page 1: Summary & Overview */}
      <Page size="A4" style={styles.page}>
        {/* Header */}
        <View style={styles.header}>
          <Text style={styles.title}>Test Results Report</Text>
          <Text style={styles.subtitle}>
            Comprehensive Analysis of RNG Algorithm Testing
          </Text>
          <Text style={styles.metadata}>
            Generated: {formatDate(data.generatedAt)}
          </Text>
          <Text style={styles.metadata}>
            Period: {formatDate(data.testPeriod.from)} -{" "}
            {formatDate(data.testPeriod.to)}
          </Text>
        </View>

        {/* Executive Summary */}
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Executive Summary</Text>
          <View style={styles.summaryGrid}>
            <View style={styles.summaryCard}>
              <Text style={styles.summaryLabel}>Total Tests</Text>
              <Text style={styles.summaryValue}>{data.summary.totalTests}</Text>
              <Text style={styles.summarySubValue}>
                {data.summary.totalAlgorithms} algorithms tested
              </Text>
            </View>

            <View style={styles.summaryCard}>
              <Text style={styles.summaryLabel}>Pass Rate</Text>
              <Text style={styles.summaryValue}>
                {formatNumber(data.summary.overallPassRate, 1)}%
              </Text>
              <Text style={styles.summarySubValue}>
                {data.summary.passedTests} passed / {data.summary.failedTests}{" "}
                failed
              </Text>
            </View>

            <View style={styles.summaryCard}>
              <Text style={styles.summaryLabel}>Test Types</Text>
              <Text style={styles.summaryValue}>
                {data.summary.totalTestTypes}
              </Text>
              <Text style={styles.summarySubValue}>Different test types</Text>
            </View>

            <View style={styles.summaryCard}>
              <Text style={styles.summaryLabel}>Avg Execution Time</Text>
              <Text style={styles.summaryValue}>
                {formatNumber(data.summary.avgExecutionTime, 0)} ms
              </Text>
              <Text style={styles.summarySubValue}>Per test average</Text>
            </View>
          </View>

          {/* Progress bar for pass rate */}
          <View style={styles.progressBarContainer}>
            <View
              style={[
                styles.progressBarFill,
                { width: `${data.summary.overallPassRate}%` },
              ]}
            />
          </View>
        </View>

        {/* Footer */}
        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
          }
          fixed
        />
      </Page>

      {/* Page 2: Algorithm Performance */}
      <Page size="A4" style={styles.page}>
        <View style={styles.section} wrap>
          <Text style={styles.sectionTitle}>
            Algorithm Performance Analysis
          </Text>
          <Text style={styles.textMuted}>
            Comprehensive metrics for all tested RNG algorithms
          </Text>

          {/* Top Algorithms Table */}
          <View style={[styles.table, styles.mt3]} wrap>
            <View style={styles.tableHeader} fixed>
              <Text style={styles.tableCellHeader}>Algorithm</Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Pass Rate
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Avg Score
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Avg Time (ms)
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Tests
              </Text>
            </View>

            {data.rngComparison.map((rng, index) => (
              <View
                key={rng.name}
                style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}
                wrap={false}
              >
                <Text style={styles.tableCell}>{rng.name}</Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(rng.passRate, 1)}%
                </Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(rng.avgScore, 2)}
                </Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(rng.avgTime, 0)}
                </Text>
                <Text style={styles.tableCellRight}>{rng.totalTests}</Text>
              </View>
            ))}
          </View>

          {/* Algorithm Performance Chart */}
          {data.chartImages?.rngComparison && (
            <View style={[styles.chartContainer, styles.mt3]}>
              <Image
                src={data.chartImages.rngComparison}
                style={styles.chartImage}
              />
              <Text style={styles.chartCaption}>
                Algorithm performance comparison
              </Text>
            </View>
          )}
        </View>

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
          }
          fixed
        />
      </Page>

      {/* Page 3: Test Type Performance */}
      <Page size="A4" style={styles.page}>
        <View style={styles.section} wrap>
          <Text style={styles.sectionTitle}>
            Test Type Performance Analysis
          </Text>
          <Text style={styles.textMuted}>
            Metrics for different NIST test types
          </Text>

          {/* Test Types Table */}
          <View style={[styles.table, styles.mt3]} wrap>
            <View style={styles.tableHeader} fixed>
              <Text style={styles.tableCellHeader}>Test Type</Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Pass Rate
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Avg Score
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Avg Time (ms)
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Tests
              </Text>
            </View>

            {data.testComparison.map((test, index) => (
              <View
                key={test.name}
                style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}
                wrap={false}
              >
                <Text style={styles.tableCell}>{test.name}</Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(test.passRate, 1)}%
                </Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(test.avgScore, 2)}
                </Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(test.avgTime, 0)}
                </Text>
                <Text style={styles.tableCellRight}>{test.totalTests}</Text>
              </View>
            ))}
          </View>

          {/* Test Performance Chart */}
          {data.chartImages?.testComparison && (
            <View style={[styles.chartContainer, styles.mt3]}>
              <Image
                src={data.chartImages.testComparison}
                style={styles.chartImage}
              />
              <Text style={styles.chartCaption}>
                Test type performance comparison
              </Text>
            </View>
          )}
        </View>

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
          }
          fixed
        />
      </Page>

      {/* Page 4: Sample Size Analysis */}
      <Page size="A4" style={styles.page}>
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Sample Size Distribution</Text>
          <Text style={styles.textMuted}>
            Analysis of test execution by sample size ranges
          </Text>

          {/* Sample Size Table */}
          <View style={[styles.table, styles.mt3]}>
            <View style={styles.tableHeader}>
              <Text style={styles.tableCellHeader}>Sample Range</Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Test Count
              </Text>
              <Text style={[styles.tableCellHeader, { textAlign: "right" }]}>
                Avg Time (ms)
              </Text>
            </View>

            {data.sampleDistribution.map((dist, index) => (
              <View
                key={dist.range}
                style={index % 2 === 0 ? styles.tableRow : styles.tableRowAlt}
              >
                <Text style={styles.tableCell}>{dist.range}</Text>
                <Text style={styles.tableCellRight}>{dist.count}</Text>
                <Text style={styles.tableCellRight}>
                  {formatNumber(dist.avgTime, 1)}
                </Text>
              </View>
            ))}
          </View>

          {/* Sample Distribution Chart */}
          {data.chartImages?.sampleDistribution && (
            <View style={[styles.chartContainer, styles.mt3]}>
              <Image
                src={data.chartImages.sampleDistribution}
                style={styles.chartImage}
              />
              <Text style={styles.chartCaption}>
                Distribution of tests across sample size ranges
              </Text>
            </View>
          )}
        </View>

        <Text
          style={styles.footer}
          render={({ pageNumber, totalPages }) =>
            `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
          }
          fixed
        />
      </Page>

      {/* Performance vs Sample Size Chart - Separate Page */}
      {data.chartImages?.performanceVsSampleSize && (
        <Page size="A4" style={styles.page}>
          <View style={styles.section}>
            <Text style={styles.sectionTitle}>Performance vs Sample Size</Text>
            <View style={styles.chartContainer}>
              <Image
                src={data.chartImages.performanceVsSampleSize}
                style={styles.chartImage}
              />
              <Text style={styles.chartCaption}>
                Execution time correlation with sample size
              </Text>
            </View>
          </View>

          <Text
            style={styles.footer}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
            }
            fixed
          />
        </Page>
      )}

      {/* Page 5: Detailed Trends (if available) */}
      {data.rngPerformanceBySamples.length > 0 && (
        <Page size="A4" style={styles.page}>
          <View style={styles.section} wrap>
            <Text style={styles.sectionTitle}>
              Performance Trends by Sample Size
            </Text>
            <Text style={styles.textMuted}>
              Detailed performance metrics across different sample sizes
            </Text>

            {/* Show all RNGs with performance data */}
            {data.rngPerformanceBySamples.map((rng) => (
              <View
                key={rng.rngId}
                style={styles.mt3}
                wrap
                minPresenceAhead={150}
              >
                <Text style={styles.sectionSubtitle}>{rng.rngName}</Text>
                <View style={styles.table} wrap>
                  <View style={styles.tableHeader} fixed>
                    <Text style={styles.tableCellHeader}>Samples</Text>
                    <Text
                      style={[styles.tableCellHeader, { textAlign: "right" }]}
                    >
                      Pass Rate
                    </Text>
                    <Text
                      style={[styles.tableCellHeader, { textAlign: "right" }]}
                    >
                      Avg Score
                    </Text>
                  </View>

                  {rng.data.map((point, index) => (
                    <View
                      key={point.samples}
                      style={
                        index % 2 === 0 ? styles.tableRow : styles.tableRowAlt
                      }
                      wrap={false}
                    >
                      <Text style={styles.tableCell}>
                        {(point.samples / 1000).toFixed(0)}k
                      </Text>
                      <Text style={styles.tableCellRight}>
                        {formatNumber(point.passRate, 1)}%
                      </Text>
                      <Text style={styles.tableCellRight}>
                        {formatNumber(point.score, 2)}
                      </Text>
                    </View>
                  ))}
                </View>
              </View>
            ))}
          </View>

          <Text
            style={styles.footer}
            render={({ pageNumber, totalPages }) =>
              `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
            }
            fixed
          />
        </Page>
      )}

      {/* Algorithm Performance Trend Charts */}
      {data.chartImages?.algorithmTrends &&
        data.chartImages.algorithmTrends.length > 0 && (
          <Page size="A4" style={styles.page}>
            <View style={styles.section} wrap>
              <Text style={styles.sectionTitle}>
                Algorithm Performance Trends
              </Text>
              <Text style={styles.textMuted}>
                Performance metrics across different sample sizes for each
                algorithm
              </Text>

              {data.chartImages.algorithmTrends.map((chart, index) => (
                <View
                  key={chart.id}
                  style={styles.mt3}
                  wrap
                  minPresenceAhead={200}
                >
                  <Text style={styles.sectionSubtitle}>{chart.title}</Text>
                  <View style={styles.chartContainer}>
                    <Image src={chart.image} style={styles.chartImage} />
                  </View>
                  {/* Legend */}
                  <View style={styles.chartLegend}>
                    <View style={styles.legendItem}>
                      <View
                        style={[
                          styles.legendBox,
                          {
                            backgroundColor:
                              data.chartImages?.chartColors?.chart1 ||
                              "#3b82f6",
                          },
                        ]}
                      />
                      <Text style={styles.legendText}>Pass Rate (%)</Text>
                    </View>
                    <View style={styles.legendItem}>
                      <View
                        style={[
                          styles.legendBox,
                          {
                            backgroundColor:
                              data.chartImages?.chartColors?.chart2 ||
                              "#10b981",
                          },
                        ]}
                      />
                      <Text style={styles.legendText}>Score</Text>
                    </View>
                  </View>
                </View>
              ))}
            </View>

            <Text
              style={styles.footer}
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
              }
              fixed
            />
          </Page>
        )}

      {/* Test Type Performance Trend Charts */}
      {data.chartImages?.testTrends &&
        data.chartImages.testTrends.length > 0 && (
          <Page size="A4" style={styles.page}>
            <View style={styles.section} wrap>
              <Text style={styles.sectionTitle}>
                Test Type Performance Trends
              </Text>
              <Text style={styles.textMuted}>
                Performance metrics across different sample sizes for each test
                type
              </Text>

              {data.chartImages.testTrends.map((chart, index) => (
                <View
                  key={chart.id}
                  style={styles.mt3}
                  wrap
                  minPresenceAhead={200}
                >
                  <Text style={styles.sectionSubtitle}>{chart.title}</Text>
                  <View style={styles.chartContainer}>
                    <Image src={chart.image} style={styles.chartImage} />
                  </View>
                  {/* Legend */}
                  <View style={styles.chartLegend}>
                    <View style={styles.legendItem}>
                      <View
                        style={[
                          styles.legendBox,
                          {
                            backgroundColor:
                              data.chartImages?.chartColors?.chart1 ||
                              "#3b82f6",
                          },
                        ]}
                      />
                      <Text style={styles.legendText}>Pass Rate (%)</Text>
                    </View>
                    <View style={styles.legendItem}>
                      <View
                        style={[
                          styles.legendBox,
                          {
                            backgroundColor:
                              data.chartImages?.chartColors?.chart2 ||
                              "#10b981",
                          },
                        ]}
                      />
                      <Text style={styles.legendText}>Score</Text>
                    </View>
                  </View>
                </View>
              ))}
            </View>

            <Text
              style={styles.footer}
              render={({ pageNumber, totalPages }) =>
                `Page ${pageNumber} of ${totalPages} | Generated by IO_RNG Dashboard`
              }
              fixed
            />
          </Page>
        )}
    </Document>
  );
};

/**
 * Generate and download PDF report
 */
export async function generatePDFReport(
  data: ReportData,
  filename: string = "rng-test-report.pdf"
): Promise<void> {
  try {
    const blob = await pdf(<PDFReport data={data} />).toBlob();
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = filename;
    link.click();
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error("Error generating PDF:", error);
    throw new Error("Failed to generate PDF report");
  }
}
